### PR TITLE
Change neighborlist dot

### PR DESCRIPTION
**Pull request by rajak7**
Following Changes have been made
1)  updated the order (from row based to column based) in which neighbor list for each stored in nbplist 2D array which is used to compute energy and force from coulomb interaction
2) Changes related to nbplist has been made in following files: init.f90, main.f90, pot.f90, qeq.f90 and pqeq.f90
3) In qeq.F90, calculation of these two dot products h_hsh(1) and  h_hsh(2) has been moved from main QEq function into get_hsh subroutine

RXMD Benchmark Results Evaluated on Cetus:
System size: [105.440 * 92.560 * 85.680] 
Total_number_of_atoms: 86_016 
Number_of_cores_used: 512 
Number_of_nodes_used: 32 
Cores/nodes used: 16 
Number of atoms per core:  168 
Number of steps run: 500 steps 
Number of threads per MPI rank: 1 

Time taken to run 500 MD steps in Cetus:
1) Original RXMD Code:  296.770 sec 
2) Updated NBP_list in RXMD: 242.53 sec
```

### CODE REVIEW

**Comment by ye-luo** [comment]
@rajak7 Please include the performance gain in the PR description

**Comment by rajak7** [comment]
updated the PR Description with benchmark results

**Comment by KenichiNomura** [comment]
I think we need to verify this code change produces the same result before merging it. Time to think of unit test and CI? I couldn't find any CI service that support Fortran btw.

**Comment by rajak7** [comment]
I have verified the all the energy terms with the original and the updated code and they are matching.
For Unit Test: Shall we just create a python scrip which just check all the energy values

**Comment by KenichiNomura** [comment]
sounds good, Pankaj. I feel it would be difficult to have a sustainable unit test from with the current code since it's not modular and cannot test unit by unit. Yes, we can check all energies values as a test but will think about it later.

**Pull request merged**
