### PR TITLE
Updated Makefile 

### PR DESCRIPTION
**Pull request by rajak7**
Makefile which is used to build rxmd software has been updated. Readme has also been updated to reflect these changes
Specifically following Changes has been made:
1) Makefile inside src and init has been updated. Here, the system config  information from the Makefile has been moved to make.inc file
2) Example make.inc files has been added inside config folder which contains main.inc files for various machines
3) A Makefile  has been added inside rxmd folder which creates geninit and rxmd executable using Makefile present in init and src folder respectively
4) Section 2.2 Confit Makefile section in Readme had been updated . Update contains the how to use Makefile and build rxmd executable and create initial geometry (using geninit) for ReaxFF simulation
5) Section 2.1 working directory in  Readme has been updated and contains newly added files (Makefile and config)

### CODE REVIEW

**Comment by ye-luo** [comment]
At the PR description, please briefly introduce what has been change, how to start using the new way, where is the documentation.

**Comment by ye-luo** [comment]
In your future development, please write more elaborate commit log. Certain changes are more than just "Update Makefile".

**Comment by rajak7** [comment]
PR has been updated and contains more elaborate description of the changes made. Reaadme file in rxmd folder contains the documentation of how to compile the code using the new Makefile in section 2.2

**Comment by KenichiNomura** [comment]
Thank you Pankaj and Ye for the updates!

**Pull request merged**
