### PR TITLE
Move rxmd binary out of src

### PR DESCRIPTION
**Pull request by rajak7**
Added softlink inside Makefile for rxmd  executable inside src directory from the home directory

### CODE REVIEW

**Comment by ye-luo** [comment]
@KenichiNomura Could you merge this?

**Comment by ye-luo** [comment]
Currently, the binary is moved from src to the top level. Every time I type make, the binary has to be linked again. It is desired that no new binary is generated at all if there is no source code change.
Having a softlink is for convenience. People are used to access the binary at the top level folder.

**Comment by ye-luo** [comment]
@KenichiNomura what do you think?

**Comment by KenichiNomura** [comment]
hm. I don't like symlink in general. How about just copy the executable instead?

**Comment by ye-luo** [comment]
Making copy is also risky due to consistency. How about directly generate the binary at the top level. There will be no more binary under src?

**Comment by KenichiNomura** [comment]
Yes, that sounds good. is Pankaj gonna make the change?

**Comment by ye-luo** [comment]
I will do the makefile change. He is busy with other code changes.

**Comment by KenichiNomura** [comment]
Thank you Ye!

**Comment by rajak7** [comment]
Done

**Comment by ye-luo** [comment]
@KenichiNomura done. rxmd binary is directly dumped at the top level folder.

**Comment by ye-luo** [comment]
@KenichiNomura Any left concerns?

**Comment by KenichiNomura** [comment]
Thank you Ye and Pankaj for taking care of it!

**Pull request merged**
